# Generated by Django 5.0.2 on 2024-02-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(null=True, upload_to='food/%Y/%m'),
        ),
        migrations.AddField(
            model_name='venue',
            name='image',
            field=models.ImageField(null=True, upload_to='venue/%Y/%m'),
        ),
    ]
