# Generated by Django 5.0.2 on 2024-02-22 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_fooditem_image_venue_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventservicebooking',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventservicebooking',
            name='service',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='customer',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_date', models.DateField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.menu')),
                ('services', models.ManyToManyField(to='app.service')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.venue')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CustomerEventBooking',
        ),
        migrations.DeleteModel(
            name='EventServiceBooking',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
